paths:
  /products:
    post:
      summary: Cria um novo produto
      tags: [products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Product'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ProductCreatedResponse'
        '400':
          description: Falha na criação do produto
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ProductCreationFailResponse'
  /products/{id}:
    get:
      summary: Obtém um produto pelo ID
      tags: [products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '404':
          description: Produto não encontrado
  /products/description/{description}:
    get:
      summary: Obtém produtos pela descrição
      tags: [products]
      parameters:
        - name: description
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Produtos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '404':
          description: Produtos não encontrados