components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
        - quantity
        - description
      properties:
        name:
          type: string
          description: Nome do produto
        price:
          type: number
          description: Preço do produto
        quantity:
          type: number
          description: Quantidade do produto
        description:
          type: string
          description: Descrição do produto
      example:
        name: Produto Exemplo
        price: 100.00
        quantity: 10
        description: Descrição do produto exemplo
    ProductCreatedResponse:
      allOf:
        - $ref: "#components/schemas/Product"
        - type: object
          required:
            - id
          properties:
            id:
              type: number
              description: O identificador do produto salvo no banco de dados
          example:
            id: 1
            name: Produto Exemplo
            price: 100.00
            quantity: 10
            description: Descrição do produto exemplo
    ProductCreationFailResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            type: string
          example:
            - "Name cannot be empty",
            - "Price must be a positive number",
            - "Quantity must be a positive number"

