components:
  schemas:
    Product:
      type: object
      required:
        - price
        - quantity
        - description
      properties:
        price:
          type: number
          description: Preço do produto
        quantity:
          type: number
          description: Quantidade do produto
        description:
          type: string
          description: Descrição do produto
      example:
        price: 100.00
        quantity: 10
        description: roupa
    ProductCreatedResponse:
      allOf:
        - $ref: "#components/schemas/Product"
        - type: object
          required:
            - id
          properties:
            id:
              type: number
              description: O identificador do produto salvo no banco de dados
          example:
            id: 1
            price: 100.00
            quantity: 10
            description: roupa
    ProductCreationFailResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            type: string
          example:
            - "description cannot be empty"
            - "Price cannot be empty"
            - "Quantity cannot be empty"